version: '3.9'
services:
  api:
    build: api/.
    restart: always
    ports:
      - "1111:1111"
    networks:
      - app-network

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "1113:80"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge