version: '3.9'
services:
  db:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Xe_3AtNwRUTBtbSa
      MYSQL_USER: doraem0070
      MYSQL_PASSWORD: P@ssword1234
    ports:
      - "3310:3310"  
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf 
      - ./localhost.sql:/docker-entrypoint-initdb.d/localhost.sql
    networks:
      - app-network

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3310
    ports:
      - "1110:80"
    networks:
      - app-network

  # web:
  #   build: app/.
  #   restart: always
  #   ports:
  #     - "3232:3232"
  #   networks:
  #     - app-network

  api:
    build: api/.
    restart: always
    ports:
      - "1112:1112"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "1111:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge