import { Prompt } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth'
import SessionProvider from '../components/common/sessionProvider'

const prompt = Prompt({ subsets: ["thai"], weight: "300" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="th" data-theme="light">
      <body className={prompt.className}>
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
      </body>
    </html>
  );
}
