import Login from "@/components/page/loginPage";
import { ToastContainer } from 'react-toastify';

export const metadata = {
    title: "เข้าสู่ระบบ",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <main className="flex justify-center items-center min-h-screen bg-gradient-to-br from-blue-600 to-blue-400">
            <Login />
            <ToastContainer />
        </main>
    );
}