import MainLayout from "@/components/layout/mainLayout"
import StationPage from "@/components/page/stationPage"

export const metadata = {
    title: "หน้าแรก",
    description: "Generated by create next app",
  };

export default function Page({ params }) {
    return (
        <MainLayout orgId={params.orgId} stationId={params.stationId}>
            <StationPage orgId={params.orgId} />
        </MainLayout>
    );
}