import MainLayout from "@/components/layout/mainLayout"
import SettingPage from "@/components/page/settingPage"
import { ToastContainer } from 'react-toastify';

export const metadata = {
    title: "ตั้งต่าการแจ้งเตือน",
    description: "Generated by create next app",
  };

export default function Page({ params }) {
    return (
        <MainLayout orgId={params.orgId} stationId={params.stationId}>
            <SettingPage orgId={params.orgId} stationId={params.stationId} />
            <ToastContainer />
        </MainLayout>
    );
}